# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Popular.create(name: "JavaScript", percentage: 55.4)
Popular.create(name: "SQL (or SQL Server)", percentage: 49.1)
Popular.create(name: "Java", percentage: 36.3)
Popular.create(name: "C#", percentage: 30.9)
Popular.create(name: "PHP", percentage: 25.9)
Popular.create(name: "Python", percentage: 24.9)
Popular.create(name: "C++", percentage: 19.4)
Popular.create(name: "C", percentage: 15.5)
Popular.create(name: "Node.js", percentage: 17.2)
Popular.create(name: "AngularJS", percentage: 17.9)
Popular.create(name: "Ruby", percentage: 8.9)
Popular.create(name: "Objective-C", percentage: 6.5)

MostWanted.create(name: "Android", percentage: 15.8)
MostWanted.create(name: "Node.js", percentage: 14.8)
MostWanted.create(name: "AngularJS", percentage: 13.4)
MostWanted.create(name: "Python", percentage: 13.3)
MostWanted.create(name: "Javascript", percentage: 11.9)
MostWanted.create(name: "React", percentage: 9.2)
MostWanted.create(name: "Swift", percentage: 8.7)
MostWanted.create(name: "MongoDB", percentage: 8.1)
MostWanted.create(name: "Arduino/Raspberry Pi", percentage: 8.0)
MostWanted.create(name: "C++", percentage: 8.0)
MostWanted.create(name: "iOS", percentage: 8.0)

Trendy.create(name: "React", percentage: 311.3)
Trendy.create(name: "Spark", percentage: 163.5)
Trendy.create(name: "Swift", percentage: 74.6)
Trendy.create(name: "Cassandra", percentage: 40.6)
Trendy.create(name: "Raspberry Pi", percentage: 36.8)
Trendy.create(name: "Node.js", percentage: 26.8)
Trendy.create(name: "Cloud", percentage: 26.0)
Trendy.create(name: "Python", percentage: 19.9)
Trendy.create(name: "Wordpress", percentage: 18.5)
Trendy.create(name: "AngularJS", percentage: 14.9)
Trendy.create(name: "Javascript", percentage: 13.0)
Trendy.create(name: "MongoDB", percentage: 10.6)
Trendy.create(name: "R", percentage: 8.8)
Trendy.create(name: "Redis", percentage: 5.8)
Trendy.create(name: "Hadoop", percentage: 5.2)
Trendy.create(name: "iOS", percentage: 3.1)
Trendy.create(name: "VBA", percentage: 2.5)
Trendy.create(name: "Android", percentage: 2.0)
Trendy.create(name: "Clojure", percentage: 2.0)
Trendy.create(name: "Go", percentage: 1.9)
